name: Subgraph Check

on:
  workflow_call:
    inputs:
      graph:
        required: true
        type: string
      variant:
        required: false
        type: string
        default: current
      name:
        required: true
        type: string
      schema_path:
        required: true
        type: string
      schema_build_cmd:
        required: false
        type: string
        default: exit 0
    secrets:
      APOLLO_KEY:
        required: true

jobs:
  check:
    runs-on: ubuntu-latest
    environment: apollo
    env:
      APOLLO_KEY: ${{ secrets.APOLLO_KEY }}
      APOLLO_VCS_COMMIT: ${{ github.event.pull_request.head.sha }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Rover
        run: |
          curl -sSL https://rover.apollo.dev/nix/v0.4.1 | sh
          echo "$HOME/.rover/bin" >> $GITHUB_PATH

      - name: Check if rover can authenticate
        run: rover config whoami

      - name: Build Schema
        run: ${{ inputs.schema_build_cmd }}

      - name:
        run: |
          rover subgraph check ${{ inputs.graph }}@${{ inputs.variant }} \
          --schema ${{ inputs.schema_path }} \
          --name ${{ inputs.name }}
